[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bk-sports-makerspace"
version = "0.0.1"
dependencies = ["pygame"]

[project.scripts]
start = "sports.__main__:main"